=== huw1990/snookerup-webapp/application/src/main/resources/routines/routine-schema.json
{
  "$id": "https://snookerup.com/routine.schema.json",
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Routine",
  "description": "Defines all fields in a routine that users can attempt in SnookerUp",
  "type": "object",
  "properties": {
    "id": {
      "description": "The ID of the routine, typically the title of the routine in lower case and kebab case.",
      "type": "string"
    },
    "title": {
      "description": "The title of the routine",
      "type": "string"
    },
    "descriptionLines": {
      "description": "A description of the routine, as an array of lines",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "variationsLinesEasier": {
      "description": "A description of variations that could make the routine easier, as an array of lines",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "variationsLinesHarder": {
      "description": "A description of variations that could make the routine harder, as an array of lines",
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "titleImage": {
      "description": "The headline image filename for the routine (matching the file in src/main/resources/static/), typically more of a thumbnail, smaller resolution image, in landscape",
      "type": "string"
    },
    "otherImages": {
      "description": "A collection of image filenames (matching files that exist in src/main/resources/static) that illustrate how to set up the routine, typically in portrait",
      "type": "array",
      "items": {
        "type": "string"
      },
      "uniqueItems": true
    },
    "tags": {
      "description": "A collection of tags/labels that describe the routine and can be used by users to search",
      "type": "array",
      "items": {
        "type": "string",
        "uniqueItems": true
      }
    },
    "unit": {
      "description": "The unit to use, when the routine supports configurable number of balls/reds",
      "type": "string",
      "enum": ["BALLS", "REDS"],
      "default": "REDS"
    },
    "variations": {
      "description": "An object containing all the possible ways a routine can be modified to vary the purpose or difficulty",
      "type": "object",
      "properties": {
        "loop": {
          "description": "Whether the routine supports looping, e.g. complete the routine then set up again and continue where you left off, where the score would be the number of completed loops.",
          "type": "boolean",
          "default": false
        },
        "cushionLimit": {
          "description": "Whether a cushion limit can be applied to the routine, e.g. complete the routine with a maximum number of times the white can hit the cushion.",
          "type": "boolean",
          "default": false
        },
        "unitNumbers": {
          "description": "If the routine supports a configurable unit (reds/balls), define them here.",
          "type": "object",
          "properties": {
            "min": {
              "description": "The minimum unit allowed. Inclusive.",
              "type": "integer"
            },
            "max": {
              "description": "The maximum unit allowed. Inclusive.",
              "type": "integer"
            }
          },
          "required": ["min", "max"]
        },
        "potInOrder": {
          "description": "Whether this routine supports the balls being potted in a specific order, where the order is up to the user.",
          "type": "boolean",
          "default": false
        },
        "stayOnOneSideOfTable": {
          "description": "Whether this routine supports a requirement for the white to always stop on one side of the table (typically left/right rather than top/bottom).",
          "type": "boolean",
          "default": false
        },
        "ballStriking": {
          "description": "The different types of ball striking supported by this routine. If not specified, the player can decide.",
          "type": "array",
          "items": {
            "type": "string",
            "enum": ["DEEP_SCREW", "SCREW", "STUN", "STUN_RUN_THROUGH", "TOP"]
          }
        }
      }
    }
  },
  "required": ["title", "descriptionLines", "titleImage"]
}

=== huw1990/snookerup-webapp/application/src/main/resources/routines/clearing-the-colours.json
{
  "id": "clearing-the-colours",
  "title": "Clearing the Colours",
  "descriptionLines": [
    "Put all colours on their spots, then try to clear them in order, i.e. yellow, green, brown, blue, pink, black."
  ],
  "variationsLinesHarder": [
    "Limiting the number of cushions the white is allowed to hit.",
    "Looping through the routine, i.e. pot yellow to black, but on the black play for position on the yellow, then replace the balls and try to clear again. With this configuration, your score is the number of completed loops."
  ],
  "titleImage": "/images/routines/clearing-the-colours-ls.png",
  "otherImages": [
    "/images/routines/clearing-the-colours.png"
  ],
  "tags": [
    "match-situations",
    "positional-play"
  ],
  "variations": {
    "loop": true,
    "cushionLimit": true
  }
}

=== huw1990/snookerup-webapp/application/src/main/resources/routines/eight-reds-with-blue-and-black.json
{
  "id": "eight-reds-with-blue-and-black",
  "title": "Eight Reds with Blue and Black",
  "descriptionLines": [
    "Place eight reds in the top half of the table (between blue and black), all in the open, as indicated in the diagram.",
    "Make a break, using only the blue and black as colours (all others aren't even on the table)."
  ],
  "variationsLinesHarder": [
    "Limiting the number of cushions the white is allowed to hit."
  ],
  "titleImage": "/images/routines/8-reds-between-blue-and-black-ls.png",
  "otherImages": [
    "/images/routines/8-reds-between-blue-and-black.png"
  ],
  "tags": [
    "break-building",
    "positional-play"
  ],
  "variations": {
    "cushionLimit": true
  }
}

=== huw1990/snookerup-webapp/application/src/main/resources/routines/the-x-line-up.json
{
  "id": "the-x-line-up",
  "title": "The X Line Up",
  "descriptionLines": [
    "A variation on the traditional Line Up routine, the X Line Up is so called because rather than the reds being arranged in one line up the table, it instead resembles an \"X\" shape.",
    "Pot the balls in order (i.e. red, colour, red, and so on), trying to make as high a break as possible.",
    "Put the reds in lines between the pink and all middle/black pockets, close to the pink. If you use all 15 reds, this should be one line of three reds, and three lines of four reds, the line with the odd red is up to you.",
    "Alternative placements of the reds include placing some below the black instead of on the \"wings\"."
  ],
  "variationsLinesEasier": [
    "For beginner and intermediate levels, don't use all 15 reds. Start with 4 reds, try to clear the table, and work your way up to the full 15."
  ],
  "variationsLinesHarder": [
    "Once you can clear a certain number of reds and all the colours, try to loop through the routine, i.e. complete the routine, then set it up and try to complete it again, playing the white on the first red from where it finished after the last black on the previous routine.",
    "Add self-imposed positional restrictions, such as limiting the number of cushions you're allowed to hit, or potting the reds in a specific order."
  ],
  "titleImage": "/images/routines/x-line-up-normal-ls.png",
  "otherImages": [
    "/images/routines/x-line-up-normal.png",
    "/images/routines/x-line-up-8-reds.png"
  ],
  "tags": [
    "break-building",
    "positional-play"
  ],
  "variations": {
    "loop": true,
    "cushionLimit": true,
    "unitNumbers": {
      "min": 4,
      "max": 15
    },
    "potInOrder": true
  }
}

=== huw1990/snookerup-webapp/application/src/main/resources/routines/three-distant-reds-and-colours.json
{
  "id": "three-distant-reds-and-colours",
  "title": "Three Distant Reds and Colours",
  "descriptionLines": [
    "This routine practises a common scenario seen in frames. It's been nip and tuck, then all of a sudden you get an opportunity where, with a few reds remaining, they're all pottable, but far apart on the table.",
    "For the setup of this routine, place one red directly between pink and black, another directly between blue and pink, and one more directly between brown and blue. Start by placing the white wherever you want, then pot all three reds with colours and clear the table.",
    "The key to this routine is picking the best route through the table, then achieving good judgement of pace to get good position each time."
  ],
  "titleImage": "/images/routines/3-distant-reds-and-colours-ls.png",
  "otherImages": [
    "/images/routines/3-distant-reds-and-colours.png"
  ],
  "tags": [
    "break-building",
    "positional-play",
    "match-situations"
  ]
}

=== huw1990/snookerup-webapp/application/src/main/resources/routines/the-t-line-up.json
{
  "id": "the-t-line-up",
  "title": "The T Line Up",
  "descriptionLines": [
    "A variation on the traditional Line Up routine, the T Line Up is so called because rather than the reds being arranged in one line up the table, it instead resembles a \"T\" shape.",
    "Pot the balls in order (i.e. red, colour, red, and so on), trying to make as high a break as possible.",
    "The typical placement sees 5 reds in a line between pink and black, then five reds each in a line either side of the pink to the side cushion.",
    "Alternative placements of the reds include placing some below the black instead of on the \"wings\"."
  ],
  "variationsLinesEasier": [
    "For beginner and intermediate levels, don't use all 15 reds. Start with 3 reds, try to clear the table, and work your way up to the full 15."
  ],
  "variationsLinesHarder": [
    "Once you can clear a certain number of reds and all the colours, try to loop through the routine, i.e. complete the routine, then set it up and try to complete it again, playing the white on the first red from where it finished after the last black on the previous routine.",
    "Add self-imposed positional restrictions, such as limiting the number of cushions you're allowed to hit, potting the reds in a specific order, or only allowing the white to be on one side of the table."
  ],
  "titleImage": "/images/routines/t-line-up-normal-ls.png",
  "otherImages": [
    "/images/routines/t-line-up-normal.png",
    "/images/routines/t-line-up-more-around-black.png",
    "/images/routines/t-line-up-10-reds.png",
    "/images/routines/t-line-up-8-reds-spread.png"
  ],
  "tags": [
    "break-building",
    "positional-play"
  ],
  "variations": {
    "loop": true,
    "cushionLimit": true,
    "unitNumbers": {
      "min": 3,
      "max": 15
    },
    "potInOrder": true,
    "stayOnOneSideOfTable": true
  }
}

=== huw1990/snookerup-webapp/application/src/main/resources/routines/the-line-up.json
{
  "id": "the-line-up",
  "title": "The Line Up",
  "descriptionLines": [
    "Arrange all reds in a line up the middle of the table, in line with the blue, pink, and black spots.",
    "Pot the balls in order (i.e. red, colour, red, and so on), trying to make as high a break as possible.",
    "Placement of the reds is up to you. Typically they are evenly spaced, including one or two above the blue, but advanced players often like to bunch the reds as much around the black as possible."
  ],
  "variationsLinesEasier": [
    "For beginner and intermediate levels, don't use all 15 reds. Start with 3 reds, try to clear the table, and work your way up to the full 15."
 ],
  "variationsLinesHarder": [
    "Once you can clear a certain number of reds and all the colours, try to loop through the routine, i.e. complete the routine, then set it up and try to complete it again, playing the white on the first red from where it finished after the last black on the previous routine.",
    "Add self-imposed positional restrictions, such as limiting the number of cushions you're allowed to hit, potting the reds in a specific order, or only allowing the white to be on one side of the table."
  ],
  "titleImage": "/images/routines/the-line-up-normal-ls.png",
  "otherImages": [
    "/images/routines/the-line-up-normal.png",
    "/images/routines/the-line-up-by-black.png",
    "/images/routines/the-line-up-seven-reds.png",
    "/images/routines/the-line-up-three-reds.png"
  ],
  "tags": [
    "break-building",
    "positional-play"
  ],
  "variations": {
    "loop": true,
    "cushionLimit": true,
    "unitNumbers": {
      "min": 3,
      "max": 15
    },
    "potInOrder": true,
    "stayOnOneSideOfTable": true
  }
}

=== huw1990/snookerup-webapp/application/src/main/resources/routines/five-reds-within-triangle.json
{
  "id": "five-reds-within-triangle",
  "title": "Five Reds Within Triangle",
  "descriptionLines": [
    "A more advanced break building and positional routine, the aim here is simple: pot five reds with five blacks, but there are some difficult restrictions and the setup is key.",
    "The reds should be arranged in a \"V\" or triangle, but with the middle reds in each line slightly further out, to give the shape a \"bulge\"",
    "Throughout the routine, each red should be potted with the white within (or near enough) the triangle formed by the reds, to make required position more difficult, and to reduce the distance the white will travel."
  ],
  "titleImage": "/images/routines/5-reds-within-triangle-ls.png",
  "otherImages": [
    "/images/routines/5-reds-within-triangle.png"
  ],
  "tags": [
    "break-building",
    "positional-play"
  ]
}

=== huw1990/snookerup-webapp/application/src/main/resources/routines/the-y-line-up.json
{
  "id": "the-y-line-up",
  "title": "The Y Line Up",
  "descriptionLines": [
    "A variation on the traditional Line Up routine, the Y Line Up is so called because rather than the reds being arranged in one line up the table, it instead resembles a \"Y\" shape.",
    "Pot the balls in order (i.e. red, colour, red, and so on), trying to make as high a break as possible.",
    "The typical placement sees 5 reds in a line between pink and black, then five reds each in a line either side of the pink to the middle pocket.",
    "Alternative placements of the reds include placing some below the black instead of on the \"wings\".",
    "This is similar to the T Line Up, but slightly more difficult in that the pink is typically out of commission, so you need to focus more on blacks."
  ],
  "variationsLinesEasier": [
    "For beginner and intermediate levels, don't use all 15 reds. Start with 3 reds, try to clear the table, and work your way up to the full 15."
  ],
  "variationsLinesHarder": [
    "Once you can clear a certain number of reds and all the colours, try to loop through the routine, i.e. complete the routine, then set it up and try to complete it again, playing the white on the first red from where it finished after the last black on the previous routine.",
    "Add self-imposed positional restrictions, such as limiting the number of cushions you're allowed to hit, or potting the reds in a specific order."
  ],
  "titleImage": "/images/routines/y-line-up-normal-ls.png",
  "otherImages": [
    "/images/routines/y-line-up-normal.png",
    "/images/routines/y-line-up-more-around-black.png",
    "/images/routines/y-line-up-10-reds.png"
  ],
  "tags": [
    "break-building",
    "positional-play"
  ],
  "variations": {
    "loop": true,
    "cushionLimit": true,
    "unitNumbers": {
      "min": 3,
      "max": 15
    },
    "potInOrder": true
  }
}
